version: '3'

services:
  reverse-proxy:
    image: traefik:v2.2
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"  # traefik API
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  model_server:
    image: registry.gitlab.inria.fr/kaldi.web/kaldi-wasm/db_server:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.model_server.rule=Host(`localhost`) && PathPrefix(`/models`)"
      - "traefik.http.routers.model_server.entrypoints=web"
    volumes:
      - ./custom_models:/model_server/public:ro
  webserver:
    image: registry.gitlab.inria.fr/kaldi.web/kaldi-wasm/webapp:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=Host(`localhost`)"
      - "traefik.http.routers.webserver.entrypoints=web"

